[workspace]
resolver = "2"
members = ["rust"]

[workspace.dependencies]
anyhow = { version = "1.0.94" }
rayon = { version = "1.10.0" }
memmap = { version = "0.7.0" }
polars = { version = "0.45.1" }

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
panic = "abort"
